alpha/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Landing.as_view()),
    path('commu/', views.Commu.as_view()),
    path('commu_qa/', views.Commu_qa.as_view()),
    path('commu_info/', views.Commu_info.as_view()),
    path('codingtest/', views.Codingtest.as_view()),
    path('codingresult/', views.coresult),
    path('delete_comment/<int:pk>/', views.delete_comment),
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()),
    path('update_post/<int:pk>/', views.CommuUpdate.as_view()),
    path('commucreate/', views.CommuCreate.as_view()),
    path('tag/<str:slug>/', views.tag_page),
    path('category/<str:slug>/', views.category_page),
    path('<int:pk>/', views.CommuDetail.as_view()),
    path('<int:pk>/new_comment/', views.new_comment),
]

port/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('alpha.urls')),
    path('markdownx/', include('markdownx.urls')),
    path('accounts/', include('allauth.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT )

alpha/models.py
from django.db import models
from django.contrib.auth.models import User
from markdownx.models import MarkdownxField
from markdownx.utils import markdown
import os
# Create your models here.
class land(models.Model):
    # title = models.CharField(max_length=20,  null=True, blank=True)
    # hook_text = models.CharField(max_length=100,  null=True, blank=True)
    content = models.TextField()

    # create_at = models.DateTimeField(auto_now_add=True)
    # update_at = models.DateTimeField(auto_now=True)

    # head_image = models.ImageField(upload_to='alpha/imges/%Y/%m/%d/', null=True, blank = True)
    # file_upload = models.FileField(upload_to='alpha/files/%Y/%m/%d/', null=True, blank = True)

    # author = models.ForeignKey(User, on_delete=models.CASCADE) 작성자를 지우면 포스트 지우는 코딩
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)  # 작성자를 지워도 포스트는 남는 코딩
    
    def get_absolute_url(self):
        return f'/codingtest/'

    def __str__(self):
        return self.content[:3]

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/category/{self.slug}/'
    

    class Meta():
        verbose_name_plural = 'Categories'

    
class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/tag/{self.slug}/'


class Post(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()

    create_at = models.DateTimeField(auto_now_add=True,)
    update_at = models.DateTimeField(auto_now=True)

    head_image = models.ImageField(upload_to='alpha/imges/%Y/%m/%d/', blank = True)
    file_upload = models.FileField(upload_to='alpha/files/%Y/%m/%d/', blank = True)

    # author = models.ForeignKey(User, on_delete=models.CASCADE) 작성자를 지우면 포스트 지우는 코딩
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)  # 작성자를 지워도 포스트는 남는 코딩

    category = models.ForeignKey(Category, null=True, on_delete=models.SET_NULL, blank=True)

    tags = models.ManyToManyField(Tag, blank=True)

    content = MarkdownxField()

    def __str__(self):
        return f'({self.pk}){self.title} :: {self.author}'

    def get_absolute_url(self):
        return f'/{self.pk}/'

    def get_file_name(self):
        return os.path.basename(self.file_upload.name)

    def get_file_ext(self):
        return self.get_file_name().split('.')[-1]
    
    def get_content_markdown(self):
        return markdown(self.content)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.author}::{self.content}'

    def get_absolute_url(self):
        return f'{self.post.get_absolute_url()}#comment-{self.pk}'
    
    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_avatar_url()
        else:
            return f'https://doitdjango.com/avatar/id/1246/c44b46630a3ec9b7/svg/{self.author.id}'


class Post_qa(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()

    create_at = models.DateTimeField(auto_now_add=True,)
    update_at = models.DateTimeField(auto_now=True)

    head_image = models.ImageField(upload_to='alpha/imges/%Y/%m/%d/', blank = True)
    file_upload = models.FileField(upload_to='alpha/files/%Y/%m/%d/', blank = True)

    # author = models.ForeignKey(User, on_delete=models.CASCADE) 작성자를 지우면 포스트 지우는 코딩
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)  # 작성자를 지워도 포스트는 남는 코딩

    category = models.ForeignKey(Category, null=True, on_delete=models.SET_NULL, blank=True)

    tags = models.ManyToManyField(Tag, blank=True)

    content = MarkdownxField()

    def __str__(self):
        return f'({self.pk}){self.title} :: {self.author}'

    def get_absolute_url(self):
        return f'/{self.pk}/'

    def get_file_name(self):
        return os.path.basename(self.file_upload.name)

    def get_file_ext(self):
        return self.get_file_name().split('.')[-1]
    
    def get_content_markdown(self):
        return markdown(self.content)

class Comment_qa(models.Model):
    post = models.ForeignKey(Post_qa, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.author}::{self.content}'

    def get_absolute_url(self):
        return f'{self.post.get_absolute_url()}#comment-{self.pk}'
    
    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_avatar_url()
        else:
            return f'https://doitdjango.com/avatar/id/1246/c44b46630a3ec9b7/svg/{self.author.id}'

class Post_info(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()

    create_at = models.DateTimeField(auto_now_add=True,)
    update_at = models.DateTimeField(auto_now=True)

    head_image = models.ImageField(upload_to='alpha/imges/%Y/%m/%d/', blank = True)
    file_upload = models.FileField(upload_to='alpha/files/%Y/%m/%d/', blank = True)

    # author = models.ForeignKey(User, on_delete=models.CASCADE) 작성자를 지우면 포스트 지우는 코딩
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)  # 작성자를 지워도 포스트는 남는 코딩

    category = models.ForeignKey(Category, null=True, on_delete=models.SET_NULL, blank=True)

    tags = models.ManyToManyField(Tag, blank=True)

    content = MarkdownxField()

    def __str__(self):
        return f'({self.pk}){self.title} :: {self.author}'

    def get_absolute_url(self):
        return f'/{self.pk}/'

    def get_file_name(self):
        return os.path.basename(self.file_upload.name)

    def get_file_ext(self):
        return self.get_file_name().split('.')[-1]
    
    def get_content_markdown(self):
        return markdown(self.content)

class Comment_info(models.Model):
    post = models.ForeignKey(Post_info, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.author}::{self.content}'

    def get_absolute_url(self):
        return f'{self.post.get_absolute_url()}#comment-{self.pk}'
    
    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_avatar_url()
        else:
            return f'https://doitdjango.com/avatar/id/1246/c44b46630a3ec9b7/svg/{self.author.id}'

alpha/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

alpha/templates/alpha/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>
    
    <title>{% block title %}base{% endblock %}</title>

</head>
<body>
    <main class="container">
    {% include 'alpha/navbar.html' %}
    {% block main_area %}
    {% endblock %}

    {% block side_area %}
    {% endblock %}
    </main>
    {% include 'alpha/footer.html' %}
    
</body>
</html>

alpha/templates/alpha/codingresult.html
{% extends 'alpha/base.html' %}

{% block title %}Coding Test{% endblock %}

{% block main_area %}

<div>
        {{ result }}
</div>

{% endblock %}

alpha/templates/alpha/codingtest.html
{% extends 'alpha/base.html' %}

{% block title %}Coding Test{% endblock %}

{% block main_area %}

<div class='col-lg-12 p-3'>
    <form method='POST' action='/codingresult/'>{% csrf_token %}
        <div class="mb-3 col-lg-12 col-sm-12 text-lg-start">
            <label for="codingtestarea" class="form-label">python testarea</label>
            <textarea class="form-control" name="cote" id="codingtestarea" rows="5"></textarea>
        </div>
        <div class='col-lg-12 col-sm-12 text-end'>
            <button class='btn btn-dark' for='codingtestarea'>검사</button>
        </div>
    </form> 
</div>

{% endblock %}

alpha/templates/alpha/commu.html
{% extends 'alpha/base.html' %}

{% block title %}ezcoding-자유게시판{% endblock %}

{% block main_area %}
<span class="col">
    {% if user.is_authenticated %}
        {% if user.is_superuser or user.is_staff %}
        <div class="d-grid justify-content-end">
            <a class='btn btn-info btn-sm mb-1' href='/commucreate/' role='button'>새글</a>
        </div>
        {% endif %}
    {% else %}
    <div class='text-end'>
        <span class='small meted'>새글(로그인 필요)</span>
    </div>
    {% endif %}
</span>
<div class='border text-center'>
    자유게시판
</div>


<h1 class='text-light'>
    {% if search_info %}
    <small class='text-muted'>{{ search_info }}</small>
    {% endif %}
    {% if category %}
    <span class='badge badge-secondary'>{{ category }}
        {% if category == '미분류' %}
        ({{ no_category_post_count }})
        {% else %}
        ({{ category.post_set.count }})
        {% endif %}
    </sapn>
    {% endif %}
    {% if tag %}
        <span class='badge badge-light'><i class='fas fa-tags'></i>{{ tag }} ({{ tag.post_set.count }})</sapn>
    {% endif %}
</h1>

<div class="card container">
    {% for p in object_list %}
    <div class='row col'>
        {% if  p.head_image %}
            <img class='card_img_top' src='{{ p.head_image.url}}' alt='Card image cap'>
        {% else %}
            <span></span>
        {% endif %}
        
            <a href='{{p.get_absolute_url}}' class='btn col card-header h5'>
            {{p.title}}
            </a>
        
            <a href='{{p.get_absolute_url}}' class='btn col-6 border-start border-end border-bottom'>
                {{ p.get_content_markdown | truncatechars_html:50 | safe }}
            </a>
        <div class='col border-end border-bottom'>
            <span class='h6'>작성자: {{p.author}}</span><span class="h6 small"><br/>작성시간: {{ p.create_at }}</span>
        </div>
    </div>
    {% endfor %}
</div>

<!-- pagination -->
<br/>
{% if is_paginated %}
<ul class="pagination justify-content-center mb-4">
{% if page_obj.has_next %}
<li class="page-item">
    <a class="page-link" href="?page={{ page_obj.next_page_number }}">&laquo;</a>
</li>
{% else %}    
<li class="page-item disabled">
<a class="page-link" href="#" aria-label="Previous">
    <span aria-hidden="true">&laquo;</span>
</a>
</li>
{% endif %}
{% if page_obj.has_previous %}
<li class="page-item">
    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&raquo;</a>
</li>
{% else %}    
<li class="page-item disabled">
<a class="page-link" href="#" aria-label="Previous">
    <span aria-hidden="true">&raquo;</span>
</a>
</li>
{% endif %}
</ul>
{% endif %}

{% endblock %}

alpha/templates/alpha/commu_best.html
{% extends 'alpha/base.html' %}

{% block title %}ezcoding-베스트게시판{% endblock %}

{% block main_area %}
<span class="col">
    {% if user.is_authenticated %}
        {% if user.is_superuser or user.is_staff %}
        <div class="d-grid justify-content-end">
            <a class='btn btn-info btn-sm mb-1' href='/commucreate/' role='button'>새글</a>
        </div>
        {% endif %}
    {% else %}
    <div class='text-end'>
        <span class='small meted'>새글(로그인 필요)</span>
    </div>
    {% endif %}
</span>
<div class='border text-center'>
    베스트게시판
</div>


<h1 class='text-light'>
    {% if search_info %}
    <small class='text-muted'>{{ search_info }}</small>
    {% endif %}
    {% if category %}
    <span class='badge badge-secondary'>{{ category }}
        {% if category == '미분류' %}
        ({{ no_category_post_count }})
        {% else %}
        ({{ category.post_set.count }})
        {% endif %}
    </sapn>
    {% endif %}
    {% if tag %}
        <span class='badge badge-light'><i class='fas fa-tags'></i>{{ tag }} ({{ tag.post_set.count }})</sapn>
    {% endif %}
</h1>

<div class="card container">
    {% for p in object_list %}
    <div class='row col'>
        {% if  p.head_image %}
            <img class='card_img_top' src='{{ p.head_image.url}}' alt='Card image cap'>
        {% else %}
            <span></span>
        {% endif %}
        
            <a href='{{p.get_absolute_url}}' class='btn col card-header h5'>
            {{p.title}}
            </a>
        
            <a href='{{p.get_absolute_url}}' class='btn col-6 border-start border-end border-bottom'>
                {{ p.get_content_markdown | truncatechars_html:50 | safe }}
            </a>
        <div class='col border-end border-bottom'>
            <span class='h6'>작성자: {{p.author}}</span><span class="h6 small"><br/>작성시간: {{ p.create_at }}</span>
        </div>
    </div>
    {% endfor %}
</div>

<!-- pagination -->
<br/>
{% if is_paginated %}
<ul class="pagination justify-content-center mb-4">
{% if page_obj.has_next %}
<li class="page-item">
    <a class="page-link" href="?page={{ page_obj.next_page_number }}">&laquo;</a>
</li>
{% else %}    
<li class="page-item disabled">
<a class="page-link" href="#" aria-label="Previous">
    <span aria-hidden="true">&laquo;</span>
</a>
</li>
{% endif %}
{% if page_obj.has_previous %}
<li class="page-item">
    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&raquo;</a>
</li>
{% else %}    
<li class="page-item disabled">
<a class="page-link" href="#" aria-label="Previous">
    <span aria-hidden="true">&raquo;</span>
</a>
</li>
{% endif %}
</ul>
{% endif %}

{% endblock %}

alpha/templates/alpha/commu_detail.html
{% extends 'alpha/base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}Post Detail{% endblock %}

{% block main_area %}

  <div class="p-2">
    <div class="container p-2">
      <div class='card'>
        {% if  post.head_image %}
        <img class='card_img_top' src='{{ post.head_image.url}}' alt='Card image cap'>
        {% else %}
        {% endif %}
        <div id='post-area'>
        <h1 class="m-0 px-2">{{ post.title }}</h3>
        
      </div>
      <span class='px-2 small text-end'>작성자 : <a href='#'>{{post.author}}</a></span>
      <span class='px-2 text-muted small text-end'>{{post.create_at}}<br/></span>
        
      {% if post.file_upload %}
      <a href='{{post.file_upload.url}}' class='btn btn-outline-dark btn-sm col-4' role='button' download>
        Download:
        {% if post.get_file_ext == 'csv' %}
        <i class="fa-solid fa-file-csv"></i>
        {% elif post.get_file_ext == 'xlsx' or post.get_file_ext == 'xls' %}
        <i class="fa-solid fa-file-excel"></i>
        {% elif post.get_file_ext == 'pdf' %}
        <i class="fa-solid fa-file-pdf"></i>
        {% elif post.get_file_ext == 'word' %}
        <i class="fa-solid fa-file-word"></i>
        {% else %}
        <i class="fa-solid fa-file"></i>
        {% endif %}
        {{ post.get_file_name}}
      </a>
      {% endif %}
      <hr/ class='mt-0 mb-1'>
      <h4 class='px-2'>{{ post.get_content_markdown | safe }}</h4>
      {% if post.tags.exists %}
      <div class='col px-0'>
        {% if post.category %}
        <span class='badge badge-secondary float-right'>{{ post.category }}</span>
        {% else %}
        <span class='badge badge-secondary float-right'>미분류</span>
        {% endif %}
        <i class="fa-solid fa-tag"></i>
        {% for tag in post.tags.all %}
          <a href='{{ tag.get_absolute_url }}'><span class='badge badge-pill badge-light'>{{ tag }}</sapn></a>
        {% endfor %}
      </div>
      {% endif %}
    </div>
    {% if user.is_authenticated and user == post.author %}
    <div class="d-grid justify-content-end">
    <a class='btn btn-info btn-sm mt-1' href='/update_post/{{ post.pk }}/' role='button'<i class='fas fa-pen'></i> Edit post</a>
    </div>
    {% endif %}
  </div>
  <!-- Comments form-->
  <div id='comment-area'>
    <div class='card m-2'>
      <div class='card-body'>
        {% if user.is_authenticated %}
        <form id='comment-form' method='POST' action='{{ post.get_absolute_url }}new_comment/'>
          {% csrf_token %}
          <div class='form-group'>
            {{comment_form | crispy }}
          </div>
          <div class="d-grid justify-content-end">
            <button type='submit' class='btn btn-info btn-sm mt-1'>Submit</button>
          </div>
        </form>
        {% else %}
        <a role='button' class='btn btn-outline-dark btn-block btn-sm' href='#' data-toggle='modal' data-target='#loginModal'>Log in and leave a comment</a>
        {% endif %}
      </div>
    </div>
  {% if post.comment_set.exists %}
    {% for comment in post.comment_set.iterator %}
    <div class='media m-3' id='comment-{{ comment.pk }}'>
      <img class='d-flex mr-3 rounded-circle' src='{{ comment.get_avatar_url }}' alt='{{ comment.author }}' width='60px'>
      <div class='media-body'>
        {% if user.is_authenticated and comment.author == user %}
        <div class='float-right'>
          <a role='button' class='btn btn-sm btn-info' id='comment-{{ comment.pk }}-update-btn' href='/update_comment/{{ comment.pk }}/'>
            edit
          </a>
          <a role='button' href='#' id='comment-{{ comment.pk }}-delete-modal-btn' class='btn btn-sm btn-danger' data-toggle='modal' data-target='#deleteCommentModal-{{ comment.pk }}'>
            delete
          </a>
        </div>
        <!-- modal -->  
        <div class='modal fade' id='deleteCommentModal-{{ comment.pk }}' tabindex='-1' role='dialog' aria-labelledby='deleteCommentModalLabel' aria-hidden='true'>
          <div class='modal-dialog' role='document'>
            <div class='modal-content'>
              <div class='modal-header'>
                <h5 class='modal-title' id='deleteCommentModalLabel'>Are You Sure?
                </h5>
                  <button type='button' class='close' data-dismiss='modal' aria-label='Close'>
                  <span aria-hidden='true'>&times;</span>
                  </button>
              </div>
              <div class='modal-body'>
                <del>{{ comment | linebreaks }}</del>
              </div>
              <div class='modal-footer'>
                <button type='button' class='btn btn-secondary' data-dismiss='modal'>Cancel</button>
                <a role='button' class'btn btn-danger' href='/blog/delete_comment/{{ comment.pk }}/'>Delete</a>
              </div>
            </div>
          </div>
        </div>
        {% endif %}
        <h5 class='mt-0'>{{ comment.author.username }} &nbsp;&nbsp;<small class='text-muted'>{{ comment.create_at }}</small></h5>
        <p>{{ comment.content | linebreaks }}</p>
        {% if comment.create_at != comment.modified_at %}
          <p class='text-muted float-right'><small>Updated: {{ comment.modified_at }}</small></p>
        {% endif %}
      </div>
    </div>
    {% endfor %}
  {% endif %}
</div>
<hr/>
{% endblock %}

alpha/templates/alpha/commu_info.html
{% extends 'alpha/base.html' %}

{% block title %}ezcoding-정보/팁 게시판{% endblock %}

{% block main_area %}
<span class="col">
    {% if user.is_authenticated %}
        {% if user.is_superuser or user.is_staff %}
        <div class="d-grid justify-content-end">
            <a class='btn btn-info btn-sm mb-1' href='/commucreate/' role='button'>새글</a>
        </div>
        {% endif %}
    {% else %}
    <div class='text-end'>
        <span class='small meted'>새글(로그인 필요)</span>
    </div>
    {% endif %}
</span>
<div class='border text-center'>
    정보/팁 게시판
</div>


<h1 class='text-light'>
    {% if search_info %}
    <small class='text-muted'>{{ search_info }}</small>
    {% endif %}
    {% if category %}
    <span class='badge badge-secondary'>{{ category }}
        {% if category == '미분류' %}
        ({{ no_category_post_count }})
        {% else %}
        ({{ category.post_set.count }})
        {% endif %}
    </sapn>
    {% endif %}
    {% if tag %}
        <span class='badge badge-light'><i class='fas fa-tags'></i>{{ tag }} ({{ tag.post_set.count }})</sapn>
    {% endif %}
</h1>

<div class="card container">
    {% for p in info_object_list %}
    <div class='row col'>
        {% if  p.head_image %}
            <img class='card_img_top' src='{{ p.head_image.url}}' alt='Card image cap'>
        {% else %}
            <span></span>
        {% endif %}
        
            <a href='{{p.get_absolute_url}}' class='btn col card-header h5'>
            {{p.title}}
            </a>
        
            <a href='{{p.get_absolute_url}}' class='btn col-6 border-start border-end border-bottom'>
                {{ p.get_content_markdown | truncatechars_html:50 | safe }}
            </a>
        <div class='col border-end border-bottom'>
            <span class='h6'>작성자: {{p.author}}</span><span class="h6 small"><br/>작성시간: {{ p.create_at }}</span>
        </div>
    </div>
    {% endfor %}
</div>

<!-- pagination -->
<br/>
{% if is_paginated %}
<ul class="pagination justify-content-center mb-4">
{% if page_obj.has_next %}
<li class="page-item">
    <a class="page-link" href="?page={{ page_obj.next_page_number }}">&laquo;</a>
</li>
{% else %}    
<li class="page-item disabled">
<a class="page-link" href="#" aria-label="Previous">
    <span aria-hidden="true">&laquo;</span>
</a>
</li>
{% endif %}
{% if page_obj.has_previous %}
<li class="page-item">
    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&raquo;</a>
</li>
{% else %}    
<li class="page-item disabled">
<a class="page-link" href="#" aria-label="Previous">
    <span aria-hidden="true">&raquo;</span>
</a>
</li>
{% endif %}
</ul>
{% endif %}

{% endblock %}

alpha/templates/alpha/commu_qa.html
{% extends 'alpha/base.html' %}

{% block title %}ezcoding-질문&답변 게시판{% endblock %}

{% block main_area %}
<span class="col">
    {% if user.is_authenticated %}
        {% if user.is_superuser or user.is_staff %}
        <div class="d-grid justify-content-end">
            <a class='btn btn-info btn-sm mb-1' href='/commucreate/' role='button'>새글</a>
        </div>
        {% endif %}
    {% else %}
    <div class='text-end'>
        <span class='small meted'>새글(로그인 필요)</span>
    </div>
    {% endif %}
</span>
<div class='border text-center'>
    질문&답변 게시판
</div>


<h1 class='text-light'>
    {% if search_info %}
    <small class='text-muted'>{{ search_info }}</small>
    {% endif %}
    {% if category %}
    <span class='badge badge-secondary'>{{ category }}
        {% if category == '미분류' %}
        ({{ no_category_post_count }})
        {% else %}
        ({{ category.post_set.count }})
        {% endif %}
    </sapn>
    {% endif %}
    {% if tag %}
        <span class='badge badge-light'><i class='fas fa-tags'></i>{{ tag }} ({{ tag.post_set.count }})</sapn>
    {% endif %}
</h1>

<div class="card container">
    {% for p in qa_object_list %}
    <div class='row col'>
        {% if  p.head_image %}
            <img class='card_img_top' src='{{ p.head_image.url}}' alt='Card image cap'>
        {% else %}
            <span></span>
        {% endif %}
        
            <a href='{{p.get_absolute_url}}' class='btn col card-header h5'>
            {{p.title}}
            </a>
        
            <a href='{{p.get_absolute_url}}' class='btn col-6 border-start border-end border-bottom'>
                {{ p.get_content_markdown | truncatechars_html:50 | safe }}
            </a>
        <div class='col border-end border-bottom'>
            <span class='h6'>작성자: {{p.author}}</span><span class="h6 small"><br/>작성시간: {{ p.create_at }}</span>
        </div>
    </div>
    {% endfor %}
</div>

<!-- pagination -->
<br/>
{% if is_paginated %}
<ul class="pagination justify-content-center mb-4">
{% if page_obj.has_next %}
<li class="page-item">
    <a class="page-link" href="?page={{ page_obj.next_page_number }}">&laquo;</a>
</li>
{% else %}    
<li class="page-item disabled">
<a class="page-link" href="#" aria-label="Previous">
    <span aria-hidden="true">&laquo;</span>
</a>
</li>
{% endif %}
{% if page_obj.has_previous %}
<li class="page-item">
    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&raquo;</a>
</li>
{% else %}    
<li class="page-item disabled">
<a class="page-link" href="#" aria-label="Previous">
    <span aria-hidden="true">&raquo;</span>
</a>
</li>
{% endif %}
</ul>
{% endif %}

{% endblock %}